name: Fedora CI

on: [push, workflow_dispatch]

permissions:
  contents: read

env:
  UBSAN_OPTIONS: print_stacktrace=1
  ASAN_OPTIONS: print_stats=1:atexit=1:detect_odr_violation=2

jobs:

  fedora-cmake-gcc:
    name: test-fedora-gcc
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v4

    - run: cat /etc/os-release

    - name: Install dependencies
      run: |
        sudo dnf -y update
        sudo dnf -y install gcc gcc-c++ libasan libasan-static libubsan libubsan-static cmake make gmp gmp-devel gmp-c++ gmp-devel gmp-static mpfr-devel
        sudo dnf upgrade

    - name: Install cppcheck
      run: |
        sudo dnf -y update
        sudo dnf -y install cppcheck

    - name: Run tests
      run: |
        cd ./tests
        chmod +x run_gcc_tests.sh && ./run_gcc_tests.sh

  fedora-cmake-clang:
    name: test-fedora-clang
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v4

    - run: cat /etc/os-release

    - name: Install dependencies
      run: |
        sudo dnf -y update
        sudo dnf -y install gcc libasan libasan-static libubsan libubsan-static clang llvm cmake make gmp gmp-devel gmp-c++ gmp-devel gmp-static mpfr-devel
        sudo dnf upgrade

    - name: Install cppcheck
      run: |
        sudo dnf -y update
        sudo dnf -y install cppcheck

    - name: Run tests
      run: |
        cd ./tests && chmod +x run_clang_tests.sh && ./run_clang_tests.sh
