name: Fedora

on: [push, pull_request, workflow_dispatch]

permissions:
    contents: read

jobs:

  fedora-cmake-gcc:
    name: test-fedora-gcc
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v3

    - run: cat /etc/os-release

    - name: Install dependencies
      run: |
        sudo dnf -y update
        sudo dnf -y install gcc gcc-c++ libasan libasan-static libubsan libubsan-static cmake make gmp gmp-devel gmp-c++ gmp-devel gmp-static mpfr-devel
        sudo dnf upgrade
    - name: Run tests
      run: |
        cd ./tests
        chmod +x ./run_gcc_tests.sh
        ./run_gcc_tests.sh

  fedora-cmake-clang:
    name: test-fedora-clang
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v3

    - run: cat /etc/os-release

    - name: Install dependencies
      run: |
        sudo dnf -y update
        sudo dnf -y install gcc libasan libasan-static libubsan libubsan-static llvm clang cmake make gmp gmp-devel gmp-c++ gmp-devel gmp-static mpfr-devel
        sudo dnf upgrade

    - name: Run tests
      run: |
        cd ./tests
        chmod +x ./run_clang_tests.sh
        ./run_clang_tests.sh
