name: Linux tests

on: [push, pull_request, workflow_dispatch]

permissions:
    contents: read

jobs:

  ubuntu-cmake:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install g++ build-essential cmake make
        sudo apt-get upgrade
    - name: Run tests
      run: |
        cd ./number_theory
        chmod +x ./run_tests.sh
        ./run_tests.sh

  fedora-cmake:
    name: fedora
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v3
    - run: cat /etc/os-release
    - name: Install dependencies
      run: |
       dnf -y update
       dnf -y install gcc-c++ cmake make
    - name: Run tests
      run: |
        cd ./number_theory
        chmod +x ./run_tests.sh
        ./run_tests.sh
