name: Ubuntu

on: [push, pull_request, workflow_dispatch]

permissions:
    contents: read

env:
    UBSAN_OPTIONS: print_stacktrace=1

jobs:

  ubuntu-cmake-gcc:
    name: test-gcc-on-ubuntu-${{ matrix.ubuntu_version }}
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [20.04, 22.04, 24.04]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install gcc g++ build-essential cmake make libgmp-dev libmpfr-dev

    - name: Run tests
      run: |
        chmod +x ./run_gcc_tests.sh
        ./run_gcc_tests.sh

  ubuntu-cmake-clang:
    name: test-clang-on-ubuntu-${{ matrix.ubuntu_version }}
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [20.04, 22.04, 24.04]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install clang llvm cmake make libgmp-dev libmpfr-dev

    - name: Run tests
      run: |
        chmod +x ./run_clang_tests.sh
        ./run_clang_tests.sh

  ubuntu-cmake-gcc-mingw-w64-i686-posix:
    name: test-gcc-mingw-w64-i686-posix-on-ubuntu-${{ matrix.ubuntu_version }}
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [22.04, 24.04]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          gcc-mingw-w64 gcc-mingw-w64-i686 gcc-mingw-w64-i686-posix gcc-mingw-w64-i686-posix-runtime \
          g++-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-i686-posix \
          mingw-w64 mingw-w64-common mingw-w64-tools mingw-w64-i686-dev \
          cmake make wine

    - name: Run tests
      run: |
        chmod +x ./run_gcc_mingw_32_tests.sh
        ./run_gcc_mingw_32_tests.sh

  ubuntu-cmake-gcc-mingw-w64-x86_64-posix:
    name: test-gcc-mingw-w64-x86_64-posix-on-ubuntu-${{ matrix.ubuntu_version }}
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [22.04, 24.04]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          gcc-mingw-w64 gcc-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix-runtime \
          g++-mingw-w64 g++-mingw-w64-x86-64-posix \
          mingw-w64 mingw-w64-common mingw-w64-tools mingw-w64-x86-64-dev \
          cmake make wine

    - name: Run tests
      run: |
        chmod +x ./run_gcc_mingw_64_tests.sh
        ./run_gcc_mingw_64_tests.sh
